Traceback (most recent call last):
  File "F:\package\wpy3\python-3.10.4.amd64\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "F:\package\wpy3\python-3.10.4.amd64\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "F:\package\wpy3\python-3.10.4.amd64\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "F:\package\wpy3\python-3.10.4.amd64\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "F:\package\wpy3\python-3.10.4.amd64\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "F:\package\wpy3\python-3.10.4.amd64\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "F:\package\wpy3\python-3.10.4.amd64\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "F:\package\wpy3\python-3.10.4.amd64\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import evclust

print(evclust.__version__)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_12592\3972515972.py[0m in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[1;33m [1;32mimport[0m [0mevclust[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;33m[0m[0m
[0;32m      3[0m [0mprint[0m[1;33m([0m[0mevclust[0m[1;33m.[0m[0m__version__[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'evclust'
ModuleNotFoundError: No module named 'evclust'

